# Generated by gnulib-tool.
#
# gnulib-tool --import --dir=. --lib=libgl --source-base=gl --m4-base=gl/m4 --libtool getopt progname strdup dummy exit error

AC_DEFUN([gl_EARLY],
[
  AC_GNU_SOURCE
  gl_USE_SYSTEM_EXTENSIONS
])

AC_DEFUN([gl_INIT],
[
  gl_ERROR
  dnl gl_USE_SYSTEM_EXTENSIONS must be added quite early to configure.ac.
  gl_GETOPT
  dnl you must add AM_GNU_GETTEXT([external]) or similar to configure.ac.
  gl_FUNC_STRDUP
  gl_FUNC_GLIBC_UNLOCKED_IO
])
